Constext
fac30/PRO04_Front_Josh_Marika_Max pull request #22
Opened 2024-10-23 22:06 UTC by MarikaBBB

The was an excess of white space beneath the footer on the shopping cart page. 

Adjusted Flex Layout:
- Applied flex-grow to the ShopCart component to allow it to expand and fill the available space between the header and footer.
Ensured the footer stays at the bottom of the viewport by leveraging a flex layout in App.tsx.

Now the ShopCart section grows naturally, filling the available space, keeping the footer in place.
Testing & Validation:
<img width="1491" alt="Screenshot 2024-10-23 at 23 04 19" src="https://github.com/user-attachments/assets/b231f960-ec37-4c02-915c-a2e57dc0cf0c">

2024-10-23 23:46 UTC, MarikaBBB commented
- IconWithText Component:
Refactored the component to use Link from react-router-dom for proper navigation handling.

- Header Component:
The Account icon now navigates to the /UserLogin route, directing users to the login page.
The Cart icon now navigates to the /ShopCart route, leading users to their shopping cart.

2024-10-24 09:47 UTC, maxitect requested changes
Sorry may have gone overboard with comments about product -> vinyl but it stems from using the interface inside utils/types.ts which reflects what is in the database that @JoshCodedit is managing

2024-10-24 09:47 UTC, maxitect commented on src/App.css
> +    flex-grow: 1;
Isn't this already defined in the tailwind class inside App.tsx? Why are we redefining it here too?

2024-10-24 09:47 UTC, maxitect commented on src/App.tsx
> +            {/* Add other routes here */}
```suggestion
```

2024-10-24 09:47 UTC, maxitect commented on src/Context/CartContext.tsx
> +}
```suggestion
import { Vinyl } from '../utils/types.ts';
```
This interface should be imported from the types @JoshCodedit added for all database schemas

2024-10-24 09:47 UTC, maxitect commented on src/Context/CartContext.tsx
> +  const calculateTotal = (items: Product[]) => {
```suggestion
  const calculateTotal = (items: Vinyl[]) => {
```

2024-10-24 09:47 UTC, maxitect commented on src/Context/CartContext.tsx
> +      .filter((item): item is Product => item !== null);
```suggestion
      .filter((item): item is Vinyl => item !== null);
```

2024-10-24 09:47 UTC, maxitect commented on src/Context/CartContext.tsx
> +  cartItems: Product[];
```suggestion
  cartItems: Vinyl[];
```

2024-10-24 09:47 UTC, maxitect commented on src/Context/CartContext.tsx
> +  addToCart: (product: Product) => void;
```suggestion
  addToCart: (vinyl: Vinyl) => void;
```

2024-10-24 09:47 UTC, maxitect commented on src/Context/CartContext.tsx
> +  const [cartItems, setCartItems] = useState<Product[]>([]);
```suggestion
  const [cartItems, setCartItems] = useState<Vinyl[]>([]);
```

2024-10-24 09:47 UTC, maxitect commented on src/Context/CartContext.tsx
> +      const newCartCount = items.reduce((acc: number, item: Product) => acc + item.quantity, 0);
```suggestion
      const newCartCount = items.reduce((acc: number, item: Vinyl) => acc + item.quantity, 0);
```

2024-10-24 09:47 UTC, maxitect commented on src/Context/CartContext.tsx
> +  const increaseQuantity = (productId: number) => {
```suggestion
  const increaseQuantity = (vinylId: number) => {
```

2024-10-24 09:47 UTC, maxitect commented on src/Context/CartContext.tsx
> +      item.id === productId ? { ...item, quantity: item.quantity + 1 } : item
```suggestion
      item.id === vinylId ? { ...item, quantity: item.quantity + 1 } : item
```

2024-10-24 09:47 UTC, maxitect commented on src/Context/CartContext.tsx
> +  const decreaseQuantity = (productId: number) => {
```suggestion
  const decreaseQuantity = (vinylId: number) => {
```

2024-10-24 09:47 UTC, maxitect commented on src/Context/CartContext.tsx
> +        if (item.id === productId) {
```suggestion
        if (item.id === vinylId) {
```

2024-10-24 09:47 UTC, maxitect commented on src/Context/CartContext.tsx
> +  const updateCartState = (updatedCart: Product[]) => {
```suggestion
  const updateCartState = (updatedCart: Vinyl[]) => {
```

2024-10-24 09:47 UTC, maxitect commented on src/pages/ShopCart.tsx
> +            cartItems.map((product) => (
```suggestion
            cartItems.map((vinyl) => (
```

2024-10-24 09:47 UTC, maxitect commented on src/pages/ShopCart.tsx
> +                  onDecrease={() => decreaseQuantity(product.id)}
```suggestion
                  quantity={vinyl.quantity}
                  onIncrease={() => increaseQuantity(vinyl.id)}
                  onDecrease={() => decreaseQuantity(vinyl.id)}
```

2024-10-24 09:47 UTC, maxitect commented on src/pages/ShopCart.tsx
> +                  <p className="font-bold text-dark">£{product.price.toFixed(2)}</p>
```suggestion
                id="vinyl"
                className="flex items-center justify-between p-4 mb-4 border border-gray-300 rounded-md bg-background-default shadow-sm"
                key={vinyl.id}
              >
                <img 
                  src={vinyl.image_url} 
                  alt={vinyl.title} 
                  className="w-24 h-24 object-cover rounded-lg"
                />
                <div className="ml-4 flex-grow">
                  <h3 className="text-lg font-medium text-text-primary">{vinyl.title}</h3>
                  <p className="text-text-secondary">{vinyl.artist}</p>
                  <p className="font-bold text-dark">£{vinyl.price.toFixed(2)}</p>
```

2024-10-28 20:58 UTC, closed without merging