Style/restyle
fac30/PRO04_Front_Josh_Marika_Max pull request #36
Opened 2024-12-30 16:42 UTC by JoshCodedit

# Pull Request Description

## Summary
This PR introduces several enhancements and updates to the project, focusing on accessibility, aesthetics, and functionality improvements.

---

## Changes Made

### Backend Integration
- **Updated Fetch Address**: Changed the fetch address to point to the EC2 instance URL for improved backend integration.

### UI Enhancements
- **Color Scheme Update**: Modified the color palette to improve accessibility while maintaining a modern and stylish appearance.
- **Product Card Depth**: Added box shadows to product cards, creating a sense of depth and improving visual hierarchy.
- **Footer Redesign**: Re-styled the footer to prioritize accessibility, ensuring better usability for all users.

### Animations
- **React Motion Integration**: Applied React Motion animations across all pages to enhance the visual experience and make element loading more dynamic and engaging.

### Accessibility Improvements
- **Accessibility Fixes**: Addressed all identified accessibility issues to ensure the project meets high standards of inclusivity and usability.

---

https://github.com/user-attachments/assets/bf825cee-b67e-449a-a152-2a8491ebeeb9

2025-01-02 10:14 UTC, maxitect requested changes
Looks amazing, love the animations using framer motion package, very pro!
Just a few minor tailwind comments to look at from me

2025-01-02 10:14 UTC, maxitect commented on src/components/common/SearchBar.tsx
> +    <div className="flex items-center space-x-2 bg-[#fff] border border-gray-300 rounded-full px-4 py-1 w-full max-w-md">
```suggestion
    <div className="flex items-center space-x-2 bg-white border border-gray-300 rounded-full px-4 py-1 w-full max-w-md">
```
Could this be bg-white instead of custom bg-[#fff]?

2025-01-02 10:14 UTC, maxitect commented on src/components/productsCard/ProductCard.tsx
> +          className="mt-4 bg-background-light text-black py-2 px-4 rounded-lg hover:bg-background-footer transition font-['Noto_Sans']"
Ideally you can create a custom tailwind class for the font in tailwind.config.js, snippet from another project:
```javascript
extend: {
      colors: {
        "clarks-orange": "#FEBC12",
        "clarks-red": "#C14627",
      },
      fontFamily: {
        jost: ["Jost", "sans-serif"],
        blanch: ["Blanch-Caps"],
        damion: ["Damion", "serif"],
        goudy: ["GoudyStd-Heavyface"],
      }
```

You could use `noto: ["Noto_Sans"]` and then call it by using `font-noto`

2025-01-02 10:14 UTC, maxitect commented on src/login-components/LoginForm.tsx
> +    <div className=" bg-background-default shadow-[0_0_15px_rgba(0,0,0,0.3)] max-w-lg max-h-[600px] m-auto flex flex-col my-10">
You could also add this shadow effect as a custom tailwind class in tailwind.config.ts, like this:
```typescript
boxShadow: {
        glow: "0px 0px 15px 0px rgba(0, 0, 0, 0.3)",
      },
```
Since this is also called in multiple places, it would make sense to keep a single source of truth for it, then you would simply call `shadow-glow` here and in `CartSummary.tsx`, `ContactusForm.tsx`, `GenreCard.tsx`, `ProductCard.tsx`, `SignUpForm.tsx` and wherever else it is used I may have missed

2025-01-02 10:14 UTC, maxitect commented on src/pages/Home.tsx
> +      className="items-center justify-center text-center px-4 py-4 flex flex-col bg-[#ffffffd8]"
```suggestion
      className="items-center justify-center text-center px-4 py-4 flex flex-col bg-white"
```
Could this just be `bg-white` aswell?

2025-01-09 09:05 UTC, JoshCodedit commented on src/components/productsCard/ProductCard.tsx
> +          className="mt-4 bg-background-light text-black py-2 px-4 rounded-lg hover:bg-background-footer transition font-['Noto_Sans']"
Yeah no problem. What I will do is create a class and call it button font as this is only used on buttons to make them stand out

2025-01-09 09:27 UTC, JoshCodedit commented on src/pages/Home.tsx
> +      className="items-center justify-center text-center px-4 py-4 flex flex-col bg-[#ffffffd8]"
This is a slightly 'off-white', i think it has a lower opacity. I can make this a class too though

2025-01-09 09:38 UTC, JoshCodedit commented on src/login-components/LoginForm.tsx
> +    <div className=" bg-background-default shadow-[0_0_15px_rgba(0,0,0,0.3)] max-w-lg max-h-[600px] m-auto flex flex-col my-10">
Good idea. I have created a new box shadow custom class

2025-01-09 11:11 UTC, maxitect approved these changes
All changes look good, thanks for improving our project!

2025-01-09 11:11 UTC, merged